/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./components/Author.vue')['default']
    CheckboxIndicator: typeof import('reka-ui')['CheckboxIndicator']
    CheckboxRoot: typeof import('reka-ui')['CheckboxRoot']
    Copyright: typeof import('./components/Copyright.vue')['default']
    Description: typeof import('./components/Description.vue')['default']
    DropdownMenuContent: typeof import('reka-ui')['DropdownMenuContent']
    DropdownMenuItem: typeof import('reka-ui')['DropdownMenuItem']
    DropdownMenuLabel: typeof import('reka-ui')['DropdownMenuLabel']
    DropdownMenuPortal: typeof import('reka-ui')['DropdownMenuPortal']
    DropdownMenuRadioGroup: typeof import('reka-ui')['DropdownMenuRadioGroup']
    DropdownMenuRadioItem: typeof import('reka-ui')['DropdownMenuRadioItem']
    DropdownMenuRoot: typeof import('reka-ui')['DropdownMenuRoot']
    DropdownMenuSeparator: typeof import('reka-ui')['DropdownMenuSeparator']
    DropdownMenuTrigger: typeof import('reka-ui')['DropdownMenuTrigger']
    ExportBtn: typeof import('./components/ExportBtn.vue')['default']
    Faq: typeof import('./components/Faq.vue')['default']
    FontSelector: typeof import('./components/FontSelector.vue')['default']
    Label: typeof import('reka-ui')['Label']
    Logo: typeof import('./components/Logo.vue')['default']
    Onlyfans: typeof import('./components/generator/Onlyfans.vue')['default']
    Pornhub: typeof import('./components/generator/Pornhub.vue')['default']
    Ribbon: typeof import('./components/Ribbon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectContent: typeof import('reka-ui')['SelectContent']
    SelectGroup: typeof import('reka-ui')['SelectGroup']
    SelectItem: typeof import('reka-ui')['SelectItem']
    SelectItemIndicator: typeof import('reka-ui')['SelectItemIndicator']
    SelectItemText: typeof import('reka-ui')['SelectItemText']
    SelectPortal: typeof import('reka-ui')['SelectPortal']
    SelectRoot: typeof import('reka-ui')['SelectRoot']
    SelectTrigger: typeof import('reka-ui')['SelectTrigger']
    SelectValue: typeof import('reka-ui')['SelectValue']
    SelectViewport: typeof import('reka-ui')['SelectViewport']
    SliderRange: typeof import('reka-ui')['SliderRange']
    SliderRoot: typeof import('reka-ui')['SliderRoot']
    SliderThumb: typeof import('reka-ui')['SliderThumb']
    SliderTrack: typeof import('reka-ui')['SliderTrack']
    Slogan: typeof import('./components/Slogan.vue')['default']
    TooltipArrow: typeof import('reka-ui')['TooltipArrow']
    TooltipContent: typeof import('reka-ui')['TooltipContent']
    TooltipPortal: typeof import('reka-ui')['TooltipPortal']
    TooltipProvider: typeof import('reka-ui')['TooltipProvider']
    TooltipRoot: typeof import('reka-ui')['TooltipRoot']
    TooltipTrigger: typeof import('reka-ui')['TooltipTrigger']
    VerticalPornHub: typeof import('./components/generator/VerticalPornHub.vue')['default']
  }
}
