/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Author: typeof import('./components/Author.vue')['default']
    CheckboxIndicator: typeof import('reka-ui')['CheckboxIndicator']
    CheckboxRoot: typeof import('reka-ui')['CheckboxRoot']
    Copyright: typeof import('./components/Copyright.vue')['default']
    Description: typeof import('./components/Description.vue')['default']
    ExportBtn: typeof import('./components/ExportBtn.vue')['default']
    Faq: typeof import('./components/Faq.vue')['default']
    FontSelector: typeof import('./components/FontSelector.vue')['default']
    ListboxContent: typeof import('reka-ui')['ListboxContent']
    ListboxItem: typeof import('reka-ui')['ListboxItem']
    ListboxRoot: typeof import('reka-ui')['ListboxRoot']
    Logo: typeof import('./components/Logo.vue')['default']
    Onlyfans: typeof import('./components/generator/Onlyfans.vue')['default']
    Pornhub: typeof import('./components/generator/Pornhub.vue')['default']
    Ribbon: typeof import('./components/Ribbon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SliderRange: typeof import('reka-ui')['SliderRange']
    SliderRoot: typeof import('reka-ui')['SliderRoot']
    SliderThumb: typeof import('reka-ui')['SliderThumb']
    SliderTrack: typeof import('reka-ui')['SliderTrack']
    Slogan: typeof import('./components/Slogan.vue')['default']
    TooltipArrow: typeof import('reka-ui')['TooltipArrow']
    TooltipContent: typeof import('reka-ui')['TooltipContent']
    TooltipPortal: typeof import('reka-ui')['TooltipPortal']
    TooltipProvider: typeof import('reka-ui')['TooltipProvider']
    TooltipRoot: typeof import('reka-ui')['TooltipRoot']
    TooltipTrigger: typeof import('reka-ui')['TooltipTrigger']
    VerticalPornHub: typeof import('./components/generator/VerticalPornHub.vue')['default']
  }
}
